spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeeapi
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9090

  servlet:
    context-path: /api